# Generated by Django 4.2.7 on 2023-11-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirDryerEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='AirReceiverEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='CIJInkJet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('photo', models.ImageField(upload_to=None)),
                ('description', models.TextField()),
                ('type', models.TextField(choices=[('KGK', 'KGK'), ('videojet', 'videojet')])),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='DODInkJet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('photo', models.ImageField(upload_to=None)),
                ('description', models.TextField()),
                ('type', models.TextField(choices=[('EVO', 'EVO'), ('p2128', 'p2128'), ('bicolor', 'bicolor')])),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='FilterEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='LaserMarkingInkJet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('photo', models.ImageField(upload_to=None)),
                ('description', models.TextField()),
                ('type', models.TextField(choices=[('uv', 'uv'), ('co2', 'co2'), ('fiber', 'fiber')])),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='NitrogenGeneratorEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='ReciprocatingCompressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('desciption', models.TextField()),
                ('type', models.CharField(choices=[('oil_free', 'oil_free'), ('oil_injected', 'oil_injected')], max_length=50)),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='RotaryScrewCompressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('desciption', models.TextField()),
                ('type', models.CharField(choices=[('oil_free', 'oil_free'), ('oil_injected', 'oil_injected')], max_length=50)),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='ScrollCompressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='SteelStanless',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('photo', models.ImageField(upload_to=None)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='TIJInkJet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('photo', models.ImageField(upload_to=None)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='TurboCompressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='WaterInvesemetEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('photo', models.ImageField(upload_to=None)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='WaterInvesemetSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
            ],
        ),
    ]
