# Generated by Django 4.2.7 on 2023-11-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_alter_lasermarkinginkjet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cijinkjet',
            name='type',
            field=models.TextField(choices=[('KGK', 'KGK'), ('videojet', 'videojet')]),
        ),
        migrations.AlterField(
            model_name='dodinkjet',
            name='type',
            field=models.TextField(choices=[('bicolor', 'bicolor'), ('EVO', 'EVO'), ('p2128', 'p2128')]),
        ),
        migrations.AlterField(
            model_name='lasermarkinginkjet',
            name='type',
            field=models.TextField(choices=[('uv', 'uv'), ('co2', 'co2'), ('fiber', 'fiber')]),
        ),
    ]
