# Generated by Django 4.2.7 on 2023-11-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_cijinkjet_type_alter_dodinkjet_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airdryerequipement',
            name='image',
            field=models.ImageField(default='', upload_to='AirDryerEquipement_Photos/%y/%m%d'),
        ),
        migrations.AddField(
            model_name='airreceiverequipement',
            name='image',
            field=models.ImageField(default='', upload_to='AirReceiverEquipement_Photos/%y/%m%d'),
        ),
        migrations.AddField(
            model_name='cijinkjet',
            name='image',
            field=models.ImageField(default='', upload_to='CIJInkJet_Photos/%y/%m%d'),
        ),
        migrations.AddField(
            model_name='dodinkjet',
            name='image',
            field=models.ImageField(default='', upload_to='DODInkJet_Photos/%y/%m%d'),
        ),
        migrations.AddField(
            model_name='filterequipement',
            name='image',
            field=models.ImageField(default='', upload_to='FilterEquipement_Photos/%y/%m%d'),
        ),
        migrations.AddField(
            model_name='lasermarkinginkjet',
            name='image',
            field=models.ImageField(default='', upload_to='_Photos/%y/%m%d'),
        ),
        migrations.AddField(
            model_name='nitrogengeneratorequipement',
            name='image',
            field=models.ImageField(default='', upload_to='NitrogenGeneratorEquipement_Photos/%y/%m%d'),
        ),
        migrations.AddField(
            model_name='reciprocatingcompressor',
            name='image',
            field=models.ImageField(default='', upload_to='ReciprocatingCompressor_Photos/%y/%m%d'),
        ),
        migrations.AddField(
            model_name='rotaryscrewcompressor',
            name='image',
            field=models.ImageField(default='', upload_to='RotaryScrewCompressor/%y/%m%d'),
        ),
        migrations.AddField(
            model_name='scrollcompressor',
            name='image',
            field=models.ImageField(default='', upload_to='_Photos/%y/%m%d'),
        ),
        migrations.AddField(
            model_name='steelstanless',
            name='image',
            field=models.ImageField(default='', upload_to='_Photos/%y/%m%d'),
        ),
        migrations.AddField(
            model_name='tijinkjet',
            name='image',
            field=models.ImageField(default='', upload_to='TIJInkJet_Photos/%y/%m%d'),
        ),
        migrations.AddField(
            model_name='turbocompressor',
            name='image',
            field=models.ImageField(default='', upload_to='TurboCompressor_Photos/%y/%m%d'),
        ),
        migrations.AddField(
            model_name='waterinvesemetequipement',
            name='image',
            field=models.ImageField(default='', upload_to='_Photos/%y/%m%d'),
        ),
        migrations.AddField(
            model_name='waterinvesemetsystem',
            name='image',
            field=models.ImageField(default='', upload_to='_Photos/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='airdryerequipement',
            name='pdf_file',
            field=models.FileField(upload_to='documents/AirDryerEquipement_pdf/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='airreceiverequipement',
            name='pdf_file',
            field=models.FileField(upload_to='documents/AirReceiverEquipement_pdf/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='cijinkjet',
            name='pdf_file',
            field=models.FileField(upload_to='documents/CIJInkJet_pdf/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='cijinkjet',
            name='type',
            field=models.TextField(choices=[('KGK', 'KGK'), ('videojet', 'videojet')]),
        ),
        migrations.AlterField(
            model_name='dodinkjet',
            name='pdf_file',
            field=models.FileField(upload_to='documents/DODInkJet_pdf/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='dodinkjet',
            name='type',
            field=models.TextField(choices=[('bicolor', 'bicolor'), ('EVO', 'EVO'), ('p2128', 'p2128')]),
        ),
        migrations.AlterField(
            model_name='filterequipement',
            name='pdf_file',
            field=models.FileField(upload_to='documents/FilterEquipement_pdf/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='lasermarkinginkjet',
            name='pdf_file',
            field=models.FileField(upload_to='documents/LaserMarkingInkJet_pdf/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='lasermarkinginkjet',
            name='type',
            field=models.TextField(choices=[('co2', 'co2'), ('uv', 'uv'), ('fiber', 'fiber')]),
        ),
        migrations.AlterField(
            model_name='nitrogengeneratorequipement',
            name='pdf_file',
            field=models.FileField(upload_to='documents/NitrogenGeneratorEquipement_pdf/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='reciprocatingcompressor',
            name='pdf_file',
            field=models.FileField(upload_to='documents/ReciprocatingCompressor_pdf/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='rotaryscrewcompressor',
            name='pdf_file',
            field=models.FileField(upload_to='documents/RotaryScrewCompressor_pdf/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='scrollcompressor',
            name='pdf_file',
            field=models.FileField(upload_to='documents/ScrollCompressor_pdf/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='steelstanless',
            name='pdf_file',
            field=models.FileField(upload_to='documents/SteelStanless_pdf/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='tijinkjet',
            name='pdf_file',
            field=models.FileField(upload_to='documents/TIJInkJet_pdf/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='turbocompressor',
            name='pdf_file',
            field=models.FileField(upload_to='documents/TurboCompressor_pdf/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='waterinvesemetequipement',
            name='pdf_file',
            field=models.FileField(upload_to='documents/WaterInvesemetEquipement_pdf/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='waterinvesemetsystem',
            name='pdf_file',
            field=models.FileField(upload_to='documents/WaterInvesemetSystem_pdf/%y/%m%d'),
        ),
    ]
