# Generated by Django 4.2.7 on 2023-11-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_airdryerequipement_image_airreceiverequipement_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cijinkjet',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='dodinkjet',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='lasermarkinginkjet',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='reciprocatingcompressor',
            name='desciption',
        ),
        migrations.RemoveField(
            model_name='rotaryscrewcompressor',
            name='desciption',
        ),
        migrations.RemoveField(
            model_name='steelstanless',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='tijinkjet',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='waterinvesemetequipement',
            name='photo',
        ),
        migrations.AddField(
            model_name='airdryerequipement',
            name='description',
            field=models.TextField(default='An Air Dryer Equipement', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='airreceiverequipement',
            name='description',
            field=models.TextField(default='An Air Receiver Equipement', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='filterequipement',
            name='description',
            field=models.TextField(default='A Filter Equipement', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='nitrogengeneratorequipement',
            name='description',
            field=models.TextField(default='A Nitrogen Generator Equipement', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='reciprocatingcompressor',
            name='description',
            field=models.TextField(default='A Reciprocating Compressor', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='rotaryscrewcompressor',
            name='description',
            field=models.TextField(default='A Rotary Screw Compressor', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='scrollcompressor',
            name='description',
            field=models.TextField(default='A Scroll Compressor', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='turbocompressor',
            name='description',
            field=models.TextField(default='A TurboC ompressor', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='waterinvesemetsystem',
            name='description',
            field=models.TextField(default='A Water Invesemet System', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='cijinkjet',
            name='description',
            field=models.TextField(default='A CIJ Ink Jet', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='cijinkjet',
            name='image',
            field=models.ImageField(default='', upload_to='CIJInkJet/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='cijinkjet',
            name='type',
            field=models.CharField(choices=[('KGK', 'KGK'), ('videojet', 'videojet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dodinkjet',
            name='description',
            field=models.TextField(default='A DOD Ink Jet', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dodinkjet',
            name='image',
            field=models.ImageField(default='', upload_to='DODInkJet/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='dodinkjet',
            name='type',
            field=models.CharField(choices=[('bicolor', 'bicolor'), ('EVO', 'EVO'), ('p2128', 'p2128')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lasermarkinginkjet',
            name='description',
            field=models.TextField(default='A Laser Marking Ink Jet', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='lasermarkinginkjet',
            name='image',
            field=models.ImageField(default='', upload_to='LaserMarkingInkJet/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='lasermarkinginkjet',
            name='type',
            field=models.CharField(choices=[('co2', 'co2'), ('uv', 'uv'), ('fiber', 'fiber')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reciprocatingcompressor',
            name='type',
            field=models.CharField(choices=[('oil_free', 'oil_free'), ('oil_injected', 'oil_injected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rotaryscrewcompressor',
            name='type',
            field=models.CharField(choices=[('oil_free', 'oil_free'), ('oil_injected', 'oil_injected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='steelstanless',
            name='description',
            field=models.TextField(default='A Steel Stanless', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='steelstanless',
            name='image',
            field=models.ImageField(default='', upload_to='SteelStanless_Photos/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='tijinkjet',
            name='description',
            field=models.TextField(default='A TIJ Ink Jet', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='tijinkjet',
            name='image',
            field=models.ImageField(default='', upload_to='TIJInkJet/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='waterinvesemetequipement',
            name='description',
            field=models.TextField(default='A Water Invesemet Equipement', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='waterinvesemetequipement',
            name='image',
            field=models.ImageField(default='', upload_to='WaterInvesemetEquipement_Photos/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='waterinvesemetsystem',
            name='image',
            field=models.ImageField(default='', upload_to='WaterInvesemetSystem_Photos/%y/%m%d'),
        ),
    ]
