# Generated by Django 4.2.7 on 2023-11-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_alter_cijinkjet_type_alter_dodinkjet_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airdryerequipement',
            options={'ordering': ['name'], 'verbose_name': 'Air Dryer Equipement'},
        ),
        migrations.AlterModelOptions(
            name='airreceiverequipement',
            options={'ordering': ['name'], 'verbose_name': 'Air Receiver Equipement'},
        ),
        migrations.AlterModelOptions(
            name='cijinkjet',
            options={'ordering': ['name'], 'verbose_name': 'CIJ Ink Jet'},
        ),
        migrations.AlterModelOptions(
            name='dodinkjet',
            options={'ordering': ['name'], 'verbose_name': 'DOD Ink Jet'},
        ),
        migrations.AlterModelOptions(
            name='filterequipement',
            options={'ordering': ['name'], 'verbose_name': 'Filter Equipement'},
        ),
        migrations.AlterModelOptions(
            name='lasermarkinginkjet',
            options={'ordering': ['name'], 'verbose_name': 'Laser Marking Ink Jet'},
        ),
        migrations.AlterModelOptions(
            name='nitrogengeneratorequipement',
            options={'ordering': ['name'], 'verbose_name': 'Nitrogen Generator Equipement'},
        ),
        migrations.AlterModelOptions(
            name='reciprocatingcompressor',
            options={'ordering': ['name'], 'verbose_name': 'Reciprocating Compressor'},
        ),
        migrations.AlterModelOptions(
            name='rotaryscrewcompressor',
            options={'ordering': ['name'], 'verbose_name': 'Rotary Screw Compressor'},
        ),
        migrations.AlterModelOptions(
            name='scrollcompressor',
            options={'ordering': ['name'], 'verbose_name': 'Scroll Compressor'},
        ),
        migrations.AlterModelOptions(
            name='steelstanless',
            options={'ordering': ['name'], 'verbose_name': 'Steel Stanless'},
        ),
        migrations.AlterModelOptions(
            name='tijinkjet',
            options={'ordering': ['name'], 'verbose_name': 'TIJ Ink Jet'},
        ),
        migrations.AlterModelOptions(
            name='turbocompressor',
            options={'ordering': ['name'], 'verbose_name': 'Turbo Compressor'},
        ),
        migrations.AlterModelOptions(
            name='waterinvesemetequipement',
            options={'ordering': ['name'], 'verbose_name': 'Water Invesemet Equipement'},
        ),
        migrations.AlterModelOptions(
            name='waterinvesemetsystem',
            options={'ordering': ['name'], 'verbose_name': ''},
        ),
        migrations.AlterField(
            model_name='airdryerequipement',
            name='image',
            field=models.ImageField(default='', upload_to='Images/AirDryerEquipement/%y/%m%d', verbose_name='Air Dryer Equipement Images '),
        ),
        migrations.AlterField(
            model_name='airdryerequipement',
            name='pdf_file',
            field=models.FileField(upload_to='documents/AirDryerEquipement/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='airreceiverequipement',
            name='image',
            field=models.ImageField(default='', upload_to='Images/AirReceiverEquipement/%y/%m%d', verbose_name='Air Receiver Equipement Images '),
        ),
        migrations.AlterField(
            model_name='airreceiverequipement',
            name='pdf_file',
            field=models.FileField(upload_to='documents/AirReceiverEquipement/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='cijinkjet',
            name='image',
            field=models.ImageField(default='', upload_to='Images/CIJInkJet/%y/%m%d', verbose_name='CIJ Ink Jet Images '),
        ),
        migrations.AlterField(
            model_name='cijinkjet',
            name='pdf_file',
            field=models.FileField(upload_to='documents/CIJInkJet/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='cijinkjet',
            name='type',
            field=models.CharField(choices=[('KGK', 'KGK'), ('videojet', 'videojet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dodinkjet',
            name='image',
            field=models.ImageField(default='', upload_to='Images/DODInkJet/%y/%m%d', verbose_name='DOD Ink Jet Images '),
        ),
        migrations.AlterField(
            model_name='dodinkjet',
            name='pdf_file',
            field=models.FileField(upload_to='documents/DODInkJet/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='dodinkjet',
            name='type',
            field=models.CharField(choices=[('p2128', 'p2128'), ('EVO', 'EVO'), ('bicolor', 'bicolor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='filterequipement',
            name='image',
            field=models.ImageField(default='', upload_to='Images/FilterEquipement/%y/%m%d', verbose_name='Filter Equipement Images '),
        ),
        migrations.AlterField(
            model_name='filterequipement',
            name='pdf_file',
            field=models.FileField(upload_to='documents/FilterEquipement/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='lasermarkinginkjet',
            name='image',
            field=models.ImageField(default='', upload_to='Images/LaserMarkingInkJet/%y/%m%d', verbose_name='Laser Marking Ink Jet Image '),
        ),
        migrations.AlterField(
            model_name='lasermarkinginkjet',
            name='pdf_file',
            field=models.FileField(upload_to='documents/LaserMarkingInkJet/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='lasermarkinginkjet',
            name='type',
            field=models.CharField(choices=[('fiber', 'fiber'), ('co2', 'co2'), ('uv', 'uv')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nitrogengeneratorequipement',
            name='image',
            field=models.ImageField(default='', upload_to='Images/NitrogenGeneratorEquipement/%y/%m%d', verbose_name='Nitrogen Generator Equipement Images '),
        ),
        migrations.AlterField(
            model_name='nitrogengeneratorequipement',
            name='pdf_file',
            field=models.FileField(upload_to='documents/NitrogenGeneratorEquipement/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='reciprocatingcompressor',
            name='image',
            field=models.ImageField(default='', upload_to='Images/ReciprocatingCompressor/%y/%m%d', verbose_name='Reciprocating Compressor Images '),
        ),
        migrations.AlterField(
            model_name='reciprocatingcompressor',
            name='pdf_file',
            field=models.FileField(upload_to='documents/ReciprocatingCompressor/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='rotaryscrewcompressor',
            name='image',
            field=models.ImageField(default='', upload_to='Images/RotaryScrewCompressor/%y/%m%d', verbose_name='Rotary Screw Compressor Images '),
        ),
        migrations.AlterField(
            model_name='rotaryscrewcompressor',
            name='pdf_file',
            field=models.FileField(upload_to='documents/RotaryScrewCompressor/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='scrollcompressor',
            name='image',
            field=models.ImageField(default='', upload_to='Images/ScrollCompressor/%y/%m%d', verbose_name='Scroll Compressor Images '),
        ),
        migrations.AlterField(
            model_name='scrollcompressor',
            name='pdf_file',
            field=models.FileField(upload_to='documents/ScrollCompressor/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='steelstanless',
            name='image',
            field=models.ImageField(default='', upload_to='Images/SteelStanless/%y/%m%d', verbose_name='Steel Stanless Images '),
        ),
        migrations.AlterField(
            model_name='steelstanless',
            name='pdf_file',
            field=models.FileField(upload_to='documents/SteelStanless/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='tijinkjet',
            name='image',
            field=models.ImageField(default='', upload_to='Images/TIJInkJet/%y/%m%d', verbose_name='TIJ Ink Jet Images '),
        ),
        migrations.AlterField(
            model_name='tijinkjet',
            name='pdf_file',
            field=models.FileField(upload_to='documents/TIJInkJet/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='turbocompressor',
            name='image',
            field=models.ImageField(default='', upload_to='Images/TurboCompressor/%y/%m%d', verbose_name='Turbo Compressor Images '),
        ),
        migrations.AlterField(
            model_name='turbocompressor',
            name='pdf_file',
            field=models.FileField(upload_to='documents/TurboCompressor/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='waterinvesemetequipement',
            name='image',
            field=models.ImageField(default='', upload_to='Images/WaterInvesemetEquipement/%y/%m%d', verbose_name='Images of Water Equipement'),
        ),
        migrations.AlterField(
            model_name='waterinvesemetequipement',
            name='pdf_file',
            field=models.FileField(upload_to='documents/WaterInvesemetEquipement/%y/%m%d'),
        ),
        migrations.AlterField(
            model_name='waterinvesemetsystem',
            name='image',
            field=models.ImageField(default='', upload_to='Images/WaterInvesemetSystem/%y/%m%d', verbose_name='Images of Water System'),
        ),
        migrations.AlterField(
            model_name='waterinvesemetsystem',
            name='pdf_file',
            field=models.FileField(upload_to='documents/WaterInvesemetSystem/%y/%m%d'),
        ),
    ]
