# Generated by Django 4.2.7 on 2024-05-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0036_alter_cijinkjet_type_alter_dodinkjet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasermarkinginkjet',
            name='type',
            field=models.CharField(choices=[('uv', 'uv'), ('co2', 'co2'), ('fiber', 'fiber')], max_length=50),
        ),
    ]
