# Generated by Django 4.2.7 on 2024-06-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0042_alter_cijinkjet_type_alter_dodinkjet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodinkjet',
            name='type',
            field=models.CharField(choices=[('EVO', 'EVO'), ('bicolor', 'bicolor'), ('p2128', 'p2128')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reciprocatingcompressor',
            name='type',
            field=models.CharField(choices=[('Oil Free', 'Oil Free'), ('Oil Injected', 'Oil Injected')], max_length=50),
        ),
    ]
