# Generated by Django 4.2.7 on 2024-06-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0045_alter_dodinkjet_type_alter_lasermarkinginkjet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cijinkjet',
            name='type',
            field=models.CharField(choices=[('videojet', 'videojet'), ('KGK', 'KGK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dodinkjet',
            name='type',
            field=models.CharField(choices=[('bicolor', 'bicolor'), ('p2128', 'p2128'), ('EVO', 'EVO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lasermarkinginkjet',
            name='type',
            field=models.CharField(choices=[('uv', 'uv'), ('fiber', 'fiber'), ('co2', 'co2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reciprocatingcompressor',
            name='type',
            field=models.CharField(choices=[('Oil Injected', 'Oil Injected'), ('Oil Free', 'Oil Free')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rotaryscrewcompressor',
            name='type',
            field=models.CharField(choices=[('oil_free', 'oil_free'), ('oil_injected', 'oil_injected')], max_length=50),
        ),
    ]
