# Generated by Django 4.2.7 on 2024-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0048_cijinkjetdescip_cijinkjetimages_dodinkjetdescip_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TIJInkJetDescip',
            new_name='CIJInkJetDescription',
        ),
        migrations.RenameModel(
            old_name='DODInkJetDescip',
            new_name='DODInkJetDescription',
        ),
        migrations.RenameModel(
            old_name='CIJInkJetDescip',
            new_name='LaserMarkingInkJetDescription',
        ),
        migrations.RenameModel(
            old_name='LaserMarkingInkJetDescip',
            new_name='TIJInkJetDescription',
        ),
        migrations.AlterModelOptions(
            name='cijinkjetdescription',
            options={'ordering': ['name'], 'verbose_name': 'CIJInkJet Description'},
        ),
        migrations.AlterModelOptions(
            name='cijinkjetimages',
            options={'ordering': ['image'], 'verbose_name': 'CIJInkJet Images'},
        ),
        migrations.AlterModelOptions(
            name='dodinkjetdescription',
            options={'ordering': ['name'], 'verbose_name': 'DODInkJet Description'},
        ),
        migrations.AlterModelOptions(
            name='dodinkjetimages',
            options={'ordering': ['image'], 'verbose_name': 'DODInkJet Image'},
        ),
        migrations.AlterModelOptions(
            name='lasermarkinginkjetdescription',
            options={'ordering': ['name'], 'verbose_name': 'LaserMarkingInkJet Description'},
        ),
        migrations.AlterModelOptions(
            name='lasermarkinginkjetimages',
            options={'ordering': ['image'], 'verbose_name': 'LaserMarkingInkJet Image '},
        ),
        migrations.AlterModelOptions(
            name='tijinkjetdescription',
            options={'ordering': ['name'], 'verbose_name': 'TIJInkJet Description'},
        ),
        migrations.AlterModelOptions(
            name='tijinkjetimages',
            options={'ordering': ['image'], 'verbose_name': 'TIJInkJet Image'},
        ),
        migrations.AddField(
            model_name='cijinkjetimages',
            name='imageName',
            field=models.CharField(default='newImage', max_length=70),
        ),
        migrations.AddField(
            model_name='dodinkjetimages',
            name='imageName',
            field=models.CharField(default='newImage', max_length=70),
        ),
        migrations.AddField(
            model_name='lasermarkinginkjetimages',
            name='imageName',
            field=models.CharField(default='newImage', max_length=70),
        ),
        migrations.AddField(
            model_name='tijinkjetimages',
            name='imageName',
            field=models.CharField(default='newImage', max_length=70),
        ),
        migrations.AlterField(
            model_name='reciprocatingcompressor',
            name='type',
            field=models.CharField(choices=[('Oil Free', 'Oil Free'), ('Oil Injected', 'Oil Injected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rotaryscrewcompressor',
            name='type',
            field=models.CharField(choices=[('oil_free', 'oil_free'), ('oil_injected', 'oil_injected')], max_length=50),
        ),
    ]
