# Generated by Django 4.2.7 on 2024-06-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0049_rename_tijinkjetdescip_cijinkjetdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciprocatingcompressor',
            name='type',
            field=models.CharField(choices=[('Oil Injected', 'Oil Injected'), ('Oil Free', 'Oil Free')], max_length=50),
        ),
    ]
