# Generated by Django 4.2.7 on 2023-11-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Catalogue Name')),
                ('language', models.CharField(max_length=50, verbose_name='catalogue language')),
                ('pdf_file', models.FileField(upload_to='documents/Catalogue/%y/%m%d')),
                ('image', models.ImageField(default='', upload_to='RotaryScrewCompressor/%y/%m%d', verbose_name='Catalogue Image')),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Explanation')),
                ('dateofEvent', models.DateField(verbose_name='Date of Event')),
                ('image', models.ImageField(default='', upload_to='LatestNews/%y/%m%d')),
            ],
        ),
        migrations.CreateModel(
            name='OurBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Branch Name')),
                ('tele', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('fax', models.CharField(max_length=15, verbose_name='Fax Number')),
                ('mail', models.EmailField(max_length=254, verbose_name='Brnach Email')),
                ('address', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=300, verbose_name='Branch Website')),
                ('location', models.URLField(max_length=300, verbose_name=' GPS link in GoogleMaps')),
            ],
        ),
        migrations.CreateModel(
            name='OurTechnologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Technology Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(default='', upload_to='RotaryScrewCompressor/%y/%m%d')),
            ],
        ),
    ]
