# Generated by Django 4.2.7 on 2023-12-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_alter_catalogue_options_alter_latestnews_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='link',
            field=models.TextField(default='https://www.facebook.com/SIDAL.SET/', verbose_name='Image of Event'),
        ),
    ]
