# Generated by Django 4.2.7 on 2023-11-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_services_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialinks',
            name='icons',
            field=models.CharField(max_length=50, verbose_name='Icon from FontAwesome.com'),
        ),
    ]
