# Generated by Django 4.2.7 on 2023-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_services_icon_alter_socialmedialinks_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialinks',
            name='color',
            field=models.CharField(default='#000', max_length=250, verbose_name='Color Of Icon'),
        ),
    ]
