# Generated by Django 4.2.7 on 2023-11-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_socialmedialinks_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalogue',
        ),
        migrations.DeleteModel(
            name='LatestNews',
        ),
        migrations.DeleteModel(
            name='OurBranches',
        ),
        migrations.DeleteModel(
            name='OurTechnologies',
        ),
    ]
