# Generated by Django 4.2.7 on 2024-05-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_aboutus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagepics',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
