# Generated by Django 4.2.7 on 2024-05-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_mainpagepics_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainviewpage',
            name='image',
            field=models.ImageField(default='', upload_to='Images/MainPage/%y/%m%d', verbose_name='Photo of Main Page'),
        ),
    ]
