# Generated by Django 4.2.7 on 2024-05-31 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_mainviewpage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='color',
        ),
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='icons',
        ),
    ]
