# Generated by Django 4.2.7 on 2024-06-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_socialmedialinks_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='messageBody',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='username',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
