# Generated by Django 4.2.7 on 2024-06-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_messagebody_contactus_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FieldName', models.CharField(max_length=50, verbose_name='Users Full Name')),
                ('FieldData', models.CharField(max_length=50, verbose_name='Users Full Name')),
            ],
            options={
                'verbose_name': 'Contact Us Information',
                'ordering': ['FieldName'],
            },
        ),
        migrations.CreateModel(
            name='ContactUsMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapURL', models.CharField(max_length=50, verbose_name='Users Full Name')),
            ],
            options={
                'verbose_name': 'Our Location On Google Map',
            },
        ),
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactUsForm',
        ),
    ]
