# Generated by Django 4.2.7 on 2024-06-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_contactusmap_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmap',
            name='mapURL',
            field=models.CharField(max_length=250, verbose_name='Copy Map URL => src="URL"'),
        ),
    ]
