/**
 
 import './ProductsContainer.css'
import {ProductCard} from '../../index'
import picis from './ProductsContainer.jpeg'
import Product1File from './ProductsContainer.jpeg'
const ProductsContainer = () => {

  const ProductCardArray = [
    { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
    { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
    { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
    { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
    { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
    { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
    { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
    { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
    { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
    { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
    
]

const CardsInfo = ProductCardArray.map(card => {
  return <ProductCard ProductName={card.ProductName} ProductType={card.ProductType} ProductFilePDF={card.ProductFilePDF} ProductImage={card.ProductImage} ProductExplain={card.ProductExplain} />
})

  return (
  <div className='ProductsContainer'>
    
    {CardsInfo}
  
  </div>
  )
}

export default ProductsContainer












// import './ProductsContainer.css'
// import {ProductCard} from '../../index'
// import picis from './ProductsContainer.jpeg'
// import Product1File from './ProductsContainer.jpeg'
// const ProductsContainer = () => {

//   const ProductCardArray = [
//     { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
//     { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
//     { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
//     { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
//     { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
//     { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
//     { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
//     { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
//     { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
//     { ProductName:'Sidal Kirkuk',ProductType:'Oil Injected',ProductFilePDF: Product1File ,ProductImage: picis,ProductExplain:' 100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance100% SIDAL KIRKUK is a high quality, oil injected reciprocating spring made of the finest natural materials. It is designed to provide superior performance' },
    
// ]

// const CardsInfo = ProductCardArray.map(card => {
//   return <ProductCard ProductName={card.ProductName} ProductType={card.ProductType} ProductFilePDF={card.ProductFilePDF} ProductImage={card.ProductImage} ProductExplain={card.ProductExplain} />
// })

//   return (
//   <div className='ProductsContainer'>
    
//     {CardsInfo}
  
//   </div>
//   )
// }

// export default ProductsContainer 
  
 */